#!/bin/bash

[ -z "$TURN_USER_NAME"     ] && TURN_USER_NAME=scope
if [ -z "$TURN_USER_PASSWORD" ]; then
  if [ ! -f "/tmp/turn-user-password" ]; then
    # Create tmp file to store a random password
    head -c 32 /dev/urandom | xxd -p | tr -d '[:cntrl:][:blank:]' > /tmp/turn-user-password
  fi
  TURN_USER_PASSWORD=$(cat /tmp/turn-user-password)
fi

[ -z "$TURN_EXTERNAL_IPV4"        ] && TURN_EXTERNAL_IPV4=127.0.0.1
[ -z "$TURN_SERVER_PORT"          ] && TURN_SERVER_PORT=3478
[ -z "$TURN_REALM_NAME"           ] && TURN_REALM_NAME=ScopeAR

echo -e "Checking service health at $TURN_EXTERNAL_IPV4:$TURN_SERVER_PORT"

/usr/local/bin/pion-client \
    -host $TURN_EXTERNAL_IPV4 \
    -realm $TURN_REALM_NAME \
    -port $TURN_SERVER_PORT \
    -user $TURN_USER_NAME=$TURN_USER_PASSWORD