#!/bin/bash

[ -z "$TURN_USER_NAME"     ] && TURN_USER_NAME=scope
[ -z "$TURN_USER_PASSWORD" ] && TURN_USER_PASSWORD=$(head -c 32 /dev/urandom | xxd -p | tr -d '[:cntrl:][:blank:]')

# Escapes characters in the password for sed.
TURN_USER_PASSWORD=${TURN_USER_PASSWORD//\\/\\\\} # \ -> \\
TURN_USER_PASSWORD=${TURN_USER_PASSWORD//\//\\/}  # / -> \/
TURN_USER_PASSWORD=${TURN_USER_PASSWORD//&/\\&}   # & -> \&
TURN_USER_PASSWORD=${TURN_USER_PASSWORD//|/\\|}   # | -> \|
TURN_USER_PASSWORD=${TURN_USER_PASSWORD//:/}      # : -> (nothing, character not allowed)

[ -z "$EXTERNAL_IPV4_ADDRESS"     ] && TURN_SERVER_PORT=127.0.0.1
[ -z "$TURN_SERVER_PORT"          ] && TURN_SERVER_PORT=3478
[ -z "$TURN_RELAY_PORT_RANGE_MIN" ] && TURN_RELAY_PORT_RANGE_MIN=49152
[ -z "$TURN_RELAY_PORT_RANGE_MAX" ] && TURN_RELAY_PORT_RANGE_MAX=65535
[ -z "$TURN_REALM_NAME"           ] && TURN_REALM_NAME=ScopeAR

/usr/local/bin/pion \ 
  -public-ip "$EXTERNAL_IPV4_ADDRESS" \
  -port "$TURN_SERVER_PORT" \ 
  -users "$TURN_USER_NAME=$TURN_USER_PASSWORD" \
  -realm "$TURN_REALM_NAME" \
  -port-range-min "$TURN_RELAY_PORT_RANGE_MIN" \ 
  -port-range-max "$TURN_RELAY_PORT_RANGE_MAX"
