#!/bin/bash

[ -z "$TURN_USER_NAME"     ] && TURN_USER_NAME=scope
if [ -z "$TURN_USER_PASSWORD" ]; then
  if [ ! -f "/tmp/turn-user-password" ]; then
    # Create tmp file to store a random password
    head -c 32 /dev/urandom | xxd -p | tr -d '[:cntrl:][:blank:]' > /tmp/turn-user-password
  fi
  TURN_USER_PASSWORD=$(cat /tmp/turn-user-password)
fi

[ -z "$EXTERNAL_IPV4_ADDRESS"     ] && EXTERNAL_IPV4_ADDRESS=127.0.0.1
[ -z "$TURN_SERVER_PORT"          ] && TURN_SERVER_PORT=3478
[ -z "$TURN_REALM_NAME"           ] && TURN_REALM_NAME=ScopeAR
[ -z "$TURN_RELAY_PORT_RANGE_MIN" ] && TURN_RELAY_PORT_RANGE_MIN=49152
[ -z "$TURN_RELAY_PORT_RANGE_MAX" ] && TURN_RELAY_PORT_RANGE_MAX=65535

echo -e "=== Start Config ==="
echo -e "\tTURN_REALM_NAME=${TURN_REALM_NAME}"
echo -e "\tEXTERNAL_IPV4_ADDRESS=${EXTERNAL_IPV4_ADDRESS}"
echo -e "\tTURN_SERVER_PORT=${TURN_SERVER_PORT}"
echo -e "\tTURN_RELAY_PORT_RANGE_MIN=${TURN_RELAY_PORT_RANGE_MIN}"
echo -e "\tTURN_RELAY_PORT_RANGE_MAX=${TURN_RELAY_PORT_RANGE_MAX}"
echo -e "=== End Config ==="

/usr/local/bin/pion-server \
  -public-ip "$EXTERNAL_IPV4_ADDRESS" \
  -port "$TURN_SERVER_PORT" \
  -users "$TURN_USER_NAME=$TURN_USER_PASSWORD" \
  -realm "$TURN_REALM_NAME" \
  -port-range-min "$TURN_RELAY_PORT_RANGE_MIN" \
  -port-range-max "$TURN_RELAY_PORT_RANGE_MAX"