version: 2.1
orbs:
  snyk: snyk/snyk@1.2.3
jobs:
  build:
    docker:
      - image: scopear/docker-base:ci-alpine3.12
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - setup_remote_docker:   
          version: 19.03.13
      - checkout
      - run:
          name: Docker Login
          command: docker_login
      - run:
          name: Build Images
          command: docker build -t "scopear/docker-pion" .
      - snyk/scan:
          docker-image-name: scopear/docker-pion
          severity-threshold: low
          token-variable: SNYK_TOKEN
          target-file: Dockerfile
          monitor-on-build: false
          fail-on-issues: false
          additional-arguments: --app-vulns --json-file-output=docker_pion_vuln.json
      - run:
          name: Snyk-to-html
          command: |
            snyk-to-html -i docker_pion_vuln.json -o docker_pion_snyk_results.html
      - store_artifacts:
          path: docker_pion_snyk_results.html
          destination: docker_pion_snyk_results.html
      - run:
          name: Push Images
          command: |
            DOCKER_IMAGE="scopear/docker-pion"
            TIMESTAMP=$(date "+%y%m%d%H%M%S")
            mkdir -p /tmp/workspace/shared-envs
            echo "export TIMESTAMP=${TIMESTAMP}" >> /tmp/workspace/shared-envs/build-envs
            [[ -z "${CIRCLE_TAG}" ]] && IMAGE_NAME="$TIMESTAMP.$CIRCLE_SHA1" || IMAGE_NAME="${CIRCLE_TAG}"
            echo "Pushing $DOCKER_IMAGE:$IMAGE_NAME ..."
            docker tag "$DOCKER_IMAGE" "$DOCKER_IMAGE:$IMAGE_NAME"
            docker push "$DOCKER_IMAGE:$IMAGE_NAME"
      - run:
          name: Create Image Artifact
          command: docker save -o docker-pion.tar scopear/docker-pion
      - store_artifacts:
          path: docker-pion.tar
          destination: docker-pion.tar
      - run:
          name: Save Image Digest env variable
          command: |
            IMAGE="scopear/docker-pion"
            mkdir -p /tmp/workspace/shared-envs
            IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' "${IMAGE}" | sed 's/\(.*\)@\(.*\)/\2/g')
            echo "export IMAGE_DIGEST=${IMAGE_DIGEST}" >> /tmp/workspace/shared-envs/build-envs
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
          - shared-envs/*

  on-prem-upload-image-to-s3:
    docker:
      - image: scopear/docker-base:ci-aws-alpine3.12
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - setup_remote_docker:   
          version: 19.03.13
      - run:
          name: Docker Login
          command: docker_login
      - run:
          name: Upload Image
          command: docker_upload_s3 "scopear/docker-pion" "$CIRCLE_TAG"

workflows:
  version: 2
  deploy:
    jobs:
      - build:
          context: scope-circleci
          filters:
            branches:
              only:
                - /develop/
            tags:
              only:
                - /^\d+\.\d+\.\d+.*/
                - /^on-prem-\d+\.\d+\.\d+.*/
                
      - on-prem-upload-image-to-s3:
          requires:
           - build
          context: scope-circleci-on-prem
          filters:
            branches:
              ignore:
                - /.*/
            tags:
              only:
                - /^on-prem-\d+\.\d+\.\d+.*$/
  
  weekly:
    triggers:
      - schedule:
          cron: "0 9 * * 0"
          filters:
            branches:
              only:
                - /develop/
    jobs:
      - build:
          context: scope-circleci
